network:
    version: 2
    ethernets:
        ens33:
            addresses: [192.168.16.3/24]
            routes:
              - to: default
                via: 192.168.16.2
            nameservers:
                addresses: [192.168.16.2]
                search: [home.arpa, localdomain]
